# Generated by Django 3.1.8 on 2021-08-14 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicbeats', '0003_favourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='favourite',
            new_name='fav',
        ),
    ]
