# Generated by Django 3.1.8 on 2021-08-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0004_auto_20210814_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fav',
        ),
    ]
