# Generated by Django 3.1.8 on 2021-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0006_favou'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favou',
        ),
    ]
