# Generated by Django 3.1.8 on 2021-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0008_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
