# Generated by Django 3.1.8 on 2021-08-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0010_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liked',
        ),
    ]
