# Generated by Django 3.1.8 on 2021-08-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicbeats', '0011_delete_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('audio_id', models.CharField(max_length=100000000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
