# Generated by Django 3.1.8 on 2021-08-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0014_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liked',
        ),
    ]
