# Generated by Django 3.1.8 on 2021-08-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0016_liked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
