# Generated by Django 3.1.8 on 2021-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0017_delete_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('Album_id', models.AutoField(primary_key=True, serialize=False)),
                ('Album_name', models.CharField(max_length=2000)),
                ('singer', models.CharField(max_length=2000)),
                ('genre', models.CharField(max_length=100)),
                ('image', models.CharField(default='', max_length=100000)),
                ('movie', models.CharField(default='', max_length=1000)),
                ('credit', models.CharField(default='', max_length=100000)),
                ('name1', models.CharField(max_length=2000)),
                ('song1', models.FileField(upload_to='images')),
                ('name2', models.CharField(max_length=2000)),
                ('song2', models.FileField(upload_to='images')),
                ('name3', models.CharField(max_length=2000)),
                ('song3', models.FileField(upload_to='images')),
                ('name4', models.CharField(max_length=2000)),
                ('song4', models.FileField(upload_to='images')),
                ('name5', models.CharField(max_length=2000)),
                ('song5', models.FileField(upload_to='images')),
            ],
        ),
    ]
