# Generated by Django 3.1.8 on 2021-08-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0018_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='song1',
            new_name='songa',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='song2',
            new_name='songb',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='song3',
            new_name='songc',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='song4',
            new_name='songd',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='song5',
            new_name='songe',
        ),
    ]
