# Generated by Django 3.2.6 on 2021-08-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0020_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comments',
        ),
    ]
